### PR TITLE
remove constraint on leading stride for dynamic layout

### PR DESCRIPTION
**Pull request by wolfv**
@ukoethe what do you think about this?

### CODE REVIEW

**Comment by wolfv** [comment]
fixes #61

**Comment by wolfv** [comment]
@ukoethe, is this change fine for you? This keeps the default behavior, but makes it configurable with a macro.
So you could e.g. use the same behavior as for row major, or just return the first/last stride, or search for the maximum stride.

Best, 

Wolf

**Comment by ukoethe** [comment]
Merde, I'm too late...

I'm a bit skeptical about the macro-based solution, for two reasons:
* I don't want xvigra behavior to deviate from native xtensor behavior if it can be at all avoided.
* I have the feeling that the macro only treats the symptom, but doesn't solve the actual problem.

Here is another code variant I tried, which gives a different error:
```c++
xtensor<double, 1> A{1, 2, 3, 4, 5};
static_shape<std::size_t, 2> shape{3, 3}, strides{1, 1};

using buffer_type = xbuffer_adaptor<double *, no_ownership, std::allocator<double>>;
using adapter_type = xarray_adaptor<buffer_type, layout_type::row_major, decltype(shape)>;
buffer_type buf(&A(0), shape[0]*shape[1], std::allocator<double>());
adapter_type A_as_matrix(buf, shape, strides);
```
This code fails with "Cannot resize with custom strides when layout() is != layout_type::dynamic.". Yet again, the check is overly restrictive, because some resize operations are clearly compatible with row_major layout (e.g. mine). 

My preferred solution is that the code checks the required properties in each particular combination of layout and strides, instead of blindly rejecting the not-so-obvious cases.

**Comment by ukoethe** [comment]
Another important reason why the customization doesn't work for me: Since the semantics of `get_leading_stride()` are undocumented, I have no idea what the appropriate customization is. Yesterday, even you were unsure if it is supposed to return the largest or smallest stride.

**Comment by wolfv** [comment]
Ok, so one problem with the combination of `static_layout` and custom strides is that we use the information about layout at compile- and run-time to select some actions (such as SIMD accelerated assign. For this to work we need to guarantee that the last stride is contiguous, and for this we rely on the static layout, which at the moment also guarantees certain properties about the strides (e.g. contiguous memory etc).
 
I agree we could potentially relax this constraint and throw a runtime_error only if the last stride is != 1 with a static layout. However, we need to make sure that we don't break any assumptions we've placed in the code so far...

For your second point: the best place to look for the definition is of course the BLAS docs. Leading stride is used to get the LDA/B/C parameter in GEMM. And indeed I was wrong yesterday, it's not the inner (smallest) stride but rather the outer largest stride (and has to be larger than `max(1, shape()[...])`
http://www.netlib.org/lapack/explore-html/d1/d54/group__double__blas__level3_gaeda3cbd99c8fb834a60a6412878226e1.html#gaeda3cbd99c8fb834a60a6412878226e1

Now, with this in mind I am wondering ... if the call will actually succeed, as your LDA would be 1 and so, by definition, should be rejected by the BLAS implementation ... or am I mistaken?

Maybe another idea would be to implement symmetric matrices and use the appropriate BLAS routines?

**Comment by ukoethe** [comment]
> I agree we could potentially relax this constraint and throw a runtime_error only if the last stride is != 1 with a static layout.

Yes, please use the least restrictive rule that's compatible with BLAS.

> However, we need to make sure that we don't break any assumptions

That's why I didn't attempt to propose a PR myself -- I just don't understand the side effects.

> as your LDA would be 1 and so, by definition, should be rejected by the BLAS implementation

I didn't dig that deep. All I can say is that with `get_leading_stride()` returning 1, the call to `linalg::dot()` succeeded and gave the expected result.

**Comment by wolfv** [comment]
you're using a matrix-matrix multiplication or matrix-vector?

**Comment by wolfv** [comment]
just checked the issue, it's matrix-vector ... i'll have another look

**Comment by ukoethe** [comment]
> it's matrix-vector

True, but it also works if `B` is a 3xM matrix (just checked for M=1 and M=2).

**Comment by wolfv** [comment]
Yes. Unfortunately, when linking against a real BLAS library (e.g. OpenBLAS) I get the following:

` ** On entry to DGEMV  parameter number  6 had an illegal value`

So we need to implement real `*SYMV` & `*SYMM` to make it work.

**Comment by ukoethe** [comment]
Just a bit of background: I want to implement image convolution by lowering it into a matrix-vector or matrix-matrix product computable by the highly optimized gemm() routine in BLAS. This is a standard technique in modern libaries, see e.g. Vasudevan et al: [Parallel Multi Channel Convolution using General Matrix Multiplication](https://arxiv.org/abs/1704.04428).

**Comment by ukoethe** [comment]
I don't quite understand the role of symmetric matrices here -- my matrices are clearly not symmetric.

**Comment by ukoethe** [comment]
> when linking against a real BLAS library

The `xtensor-blas` I downloaded from https://conda.anaconda.org/QuantStack/ lists (and installed) openblas as a dependency. How come that I didn't link against a real BLAS library?

**Comment by wolfv** [comment]
ok so maybe we need to clarify this a bit more in the docs.
xtensor-blas ships with FLENS which, besides C++ headers for BLAS/LAPACK contains a stand-alone, pure C++ implementation of BLAS routines. 
These BLAS routines are quite handy when you deal with e.g. non-matching value types (double & float etc), as they'll still work, or other C++ types such as arbitrary precision numbers.
However, they're by far not as fast as the real BLAS (and apparently not as restrictive).

To link against the real deal, we still require to add the following in the cmake:

```
add_definitions(-DHAVE_CBLAS=1)

find_package(LAPACK)
find_package(BLAS)
message(STATUS "BLAS VENDOR:    " ${BLA_VENDOR})  # optional
message(STATUS "BLAS LIBRARIES: " ${BLAS_LIBRARIES})  # optional
target_link_libraries(tutorial ${BLAS_LIBRARIES} ${LAPACK_LIBRARIES})
```

I agree that the documentation on this is not sufficient, and maybe we should have some automated mechanism in CMake to do this.

**Comment by JohanMabille** [comment]
`row_major` and `column_major` static layout imply the following unvariants:

- the size of the underlying container is the product of the shape's elements
- elements of the container are contiguous in memory

Strides are computed accordingly, allowing optimizations when assigning an expression to another. For instance in `lhs = rhs`, if both expressions have the same static layout and this one is either `row_major` or `column_major`, we can perform a straightforward 1-d assignment on the underlying containers, without checking the strides.

Besides, xtensor broadcasting mechanism relies on `backstrides`, which are the amounts needed to go back  to the beginning of a `row`, `column` or any dimension when you've reached the end. There is one `backstride` per dimension, meaning this amount must be the same for all the `rows` / `columns`. Thus using the shape and strides you propose, the following leads to incorrect result (if not a crash,I didn't try):

```cpp
xt::xarray<double, layout_type::dynamic> a({3, 3}, {1, 1}); 
// ... fill a with some value
xt::xarray<double, layout_type::row_major> b({3, 3, 3}, 2):
xt::xarray<double> res = a + b;
```

Put another way, `xtensor` broadcast mechanism assumes that the strides are somehow the cumulative products of elements of the shape. We didn't add a check mechanism for that (because at the time we implement it, we didn't think of such strides schemes), and I think we can allow this breaking behavior for `dynamic_layout` for now, but clearly not for `row_major` nor `column_major` layouts.

The solution based on the macro is indeed a quickfix, a real fix would be to define a new container type that ensure the previous rules / unvariants are not broken.

**Comment by wolfv** [comment]
given that you want to do something really advanced, it could also be a good choice to use `gemv`/`gemm` directly?

They are available in two different fashions:
The raw one from FLENS (example from `xblas.hpp`)

```
cxxblas::gemv<blas_index_t>(
            get_blas_storage_order(result),
            transpose_A ? cxxblas::Transpose::Trans : cxxblas::Transpose::NoTrans,
            static_cast<blas_index_t>(dA.shape()[0]),
            static_cast<blas_index_t>(dA.shape()[1]),
            alpha,
            dA.raw_data() + dA.raw_data_offset(),
            get_leading_stride(dA),
            dx.raw_data() + dx.raw_data_offset(),
            get_leading_stride(dx),
            beta,
            result.raw_data() + result.raw_data_offset(),
            get_leading_stride(result)
        );
```

or the one from xblas.hpp (but this one might come with some restrictions, and it might copy your data if it encounters an xexpression... signature is the following:

```
    template <class E1, class E2, class R, class value_type = typename E1::value_type>
    void gemv(const xexpression<E1>& A, const xexpression<E2>& x,
              R& result,
              bool transpose_A = false,
              const value_type& alpha = value_type(1.0),
              const value_type& beta = value_type(0.0))
```

**Comment by ukoethe** [comment]
> To link against the real BLAS, we still require to add the following in the cmake:

Ok, I also get the error you listed now. I still find it confusing that `xtensor-blas` installs openblas, but uses FLENS. Documenting it woudn't help much, because no-one consults the documentation for a simple `conda install`.

**Comment by wolfv** [comment]
Ok, we should discuss this... we can probably default CMake to link against BLAS if available, and otherwise print a warning.

Regarding the convolution, having some convolution algorithm in xtensor-blas or xtensor is definitly also an interest of ours. I looked at the paper... but I think looking at pseudo-code or an implementaiton would be more helpful. 

Looking forward to see what you're coming up with!

**Pull request merged**
