### PR TITLE
Fix inverse on 1x1 matrix

### LINKED ISSUE #74: xt::linalg::inv fails for 1x1 matrices
`xt::linalg::inv` fails for 1x1 matrices, since `xt::xarray::strides` returns `{0,0}`. The following produces a runtime error:

```cpp
#include <xtensor/xarray.hpp>
#include <xtensor-blas/xlinalg.hpp>

int main()
{
  xt::xarray<double> A = xt::zeros<double>({1, 1});
  auto B = xt::linalg::inv(A);
}
```

```
** On entry to DGETRF, parameter number  4 had an illegal value
info = -4
Assertion failed: (info>=0), function getrf, file XXX/xflens/cxxlapack/interface/getrf.tcc, line 87.
```

### PR DESCRIPTION
**Pull request by wolfv**
This fixes #74 and adds a test for #66

### CODE REVIEW

**Comment by wolfv** [comment]
what's going on with travis ... :/

**Comment by SylvainCorlay** [comment]
I reported the bug on travis yesterday. A lot of failure with apt...

**Comment by SylvainCorlay** [comment]
I am enclined to merge despite of travis' outage...

**Comment by edgarriba** [comment]
We

**Comment by wolfv** [comment]
Hi @edgarriba :wave:

**Pull request merged**
