### PR TITLE
many tests for dot, and bug fixes around transpose + dot

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
tests fail because xtensor master is required.

@JohanMabille / @SylvainCorlay can we make a new release for xtensor? the stridedview layout / transpose layout fix is required.

**Comment by SylvainCorlay** [comment]
I am ok with a `0.13.2`.

**Comment by wolfv** [comment]
:tada:

**Comment by JohanMabille** [comment]
👍

**Comment by SylvainCorlay** [comment]
You probably want to update the requirements in the readme.

**Comment by wolfv** [comment]
Updated in the table.

**Comment by SylvainCorlay** [comment]
👍 sorry, I don't know how I was looking a it.

**Pull request merged**
