### PR TITLE
Add clang-cl support

### PR DESCRIPTION
**Pull request by robertodr**
- Set up Azure pipeline to test clang-cl
- Fix test/CMakeLists.txt for new compiler. ~Note that I have bumped CMake minimum required version for the tests to 3.8. That's the version that learnt about C++17.~ I have reworked the check on C++ standard availability using [this](https://github.com/dev-cafe/cmake-cookbook/blob/master/chapter-07/recipe-03/README.md)
- On Azure, testing is done for linking against MKL downloaded from Conda. Probably the same could be done for Appveyor.

This is the [Azure build logs](https://dev.azure.com/robertodr/xtensor-blas/_build?definitionId=8&_a=summary)
You'll need an Azure free account and set up pipelines to actually use the YAML file. The badge in `README.md` should also be adjusted accordingly.

### CODE REVIEW

**Comment by JohanMabille** [comment]
> Note that I have bumped CMake minimum required version for the tests to 3.8. That's the version that learnt about C++17.

Ubuntu 16.04 comes with cmake 3.5, this change would prevent users from building xtensor-blas unit tests. Not that I am against this change, but this should be discussed with @SylvainCorlay @wolfv and @tdegeus .

Is that possible to put this change in a dedicated PR so it does not block this one?

**Comment by robertodr** [comment]
> Is that possible to put this change in a dedicated PR so it does not block this one?
Sure thing!

**Comment by robertodr** [comment]
I won't be opening the other PR to bump CMake. I think the current mechanism to check C++ standard availability suffices  and there wouldn't be much point to raise CMake requirement just so that `set(CMAKE_CXX_STANDARD 17)` works.

**Comment by robertodr** [comment]
I'll rebase and un-WIP once there's a new xtensor release with the changes in QuantStack/xtensor#1559

**Comment by robertodr** [comment]
@JohanMabille is there a timeline on the next xtensor release that includes the clang-cl changes?

**Comment by SylvainCorlay** [comment]
@robertodr that should be *very soon*, in the next couple of days.

**Comment by JohanMabille** [comment]
@robertodr We just released xtensor 0.20.6. I'll merge this and release xtensor-blas once you've rebased.

**Pull request merged**
